version: '3.8'
services:
  backend:
    build:
      context: ./backend   
      dockerfile: Dockerfile
    ports:
      - "3001:3001"       
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/prismadb?schema=public
    depends_on:
      - db
    volumes:
      - /app/node_modules  
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend   
      dockerfile: Dockerfile
    ports:
      - "8000:8000"         
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prismadb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
